AY2425S1-CS2103T-W10-1/tp

docs/_config.yml, docs/_sass/minima/_base.scss
=> Update website header

README.md
=> Updates the Readme for teacher's pet

README.md
=> Improves the quality of the readme

README.md
=> Removes extra acknowledgment from Readme

README.md
=> Removes duplicate information in ReadMe

docs/DeveloperGuide.md
=> Edit developer guide

docs/team/gabriellegtw.md
Fixes #51 
Reopen milestone because gabriellegtw's progress not captured on cs2103t website/dashboard
=> Edit gabriellegtw.md

docs/DeveloperGuide.md
=> Format Website (DG)

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/StudentId.java
=> Add auto formatting for StudentId and NetId 

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java
=> Adds specific feedback to user for wrong delete inputs

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Major.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Year.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/NameTest.java
=> Make Year, Major and NUS Net ID optional Fields

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
=> Modifies delete test cases

README.md, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/stubs/delete/ModelManagerStub.java
=> Adds delete test case and stub model

src/main/java/seedu/address/logic/Messages.java
=> Fix output message for add command

docs/UserGuide.md, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/CompositePredicate.java, src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/StudentIdMatchesPredicate.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
closes #76 
- **Prefix Alignment**: Updated the prefix format to match the project's default. The name prefix has been changed from `/n` to `n/`, and the student ID prefix has been changed from /id to id/.
- **Full Word Matching**: Implemented logic to match full words in the person's name against the provided keywords, instead of earlier partial matching
- `FindCommandTest`
- `FindCommandParserTest`
=> Improve find command

src/main/java/seedu/address/logic/commands/EditCommand.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Fixes #84 
This excludes those test cases with tags involved
=> Fix Edit test cases

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java, src/test/java/seedu/address/stubs/delete/ModelManagerStub.java
Improves delete feature custom feedback to users and improves test cases for delete.
=> Improves delete feature tailored feedback and tests

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java
=> Fixes overflow of integer error message for parsing index

src/main/java/seedu/address/commons/util/StringUtil.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
=> Fixes prefix handling of signs

src/main/java/seedu/address/logic/commands/CommentCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/CommentCommandParser.java, src/main/java/seedu/address/model/person/Comment.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Branch comment feature

src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ClearCommandParser.java, src/main/java/seedu/address/logic/parser/ExitCommandParser.java, src/main/java/seedu/address/logic/parser/HelpCommandParser.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
=> Add parser for clear, exit and help commands

docs/UserGuide.md, src/main/resources/view/DarkTheme.css
=> Change tone of user guide

docs/UserGuide.md
=> Improve quality of user guide and partition

docs/UserGuide.md
=> Fix naming bug in user guide

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/RandomCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/RandomCommandParser.java
=> Add random command and the associated parser

src/main/java/seedu/address/logic/commands/OfflineHelpCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/OfflineHelpCommandParser.java
Fixes #128 
Using the normal help command, users would be unable to access it if there do not have wifi connection
Let's add this feature which is like the help command but instead it lists the commands for the users within the jar file itself
=> Add OfflineHelp feature

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml
=> Improve Person Model in UML

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Major.java, src/main/java/seedu/address/model/person/Year.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/MajorTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java
fixes #145
Also, improves implementation of optional fields to be more in line with OOP principles
=> Add removal of optional fields

docs/UserGuide.md, docs/diagrams/add-remark/CommentClass.puml, src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/commands/CommentCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/CommentCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Comment.java, src/main/resources/view/Extensions.css, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/CommentCommandTest.java, src/test/java/seedu/address/stubs/delete/ModelManagerStub.java
Fixes #160 
Fixes #149 
Fixes #159 
Fixes #152
=> Improve code quality with add comment test cases

src/main/java/seedu/address/logic/commands/CommentCommand.java
=> Fix bug for index in comment

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/ShowCommand.java, src/main/java/seedu/address/logic/parser/OfflineHelpCommandParser.java, src/main/java/seedu/address/logic/parser/ShowCommandParser.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/group/Group.java, src/main/java/seedu/address/model/group/GroupContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/ShowCommandTest.java, src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Fix alpha bugs for show and offlinehelp

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/parser/ClearCommandParser.java, src/main/java/seedu/address/logic/parser/CommentCommandParser.java, src/main/java/seedu/address/logic/parser/ExitCommandParser.java, src/main/java/seedu/address/logic/parser/HelpCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
=> Branch fix alpha bugs

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/ArgumentMultimap.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/list/GroupList.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/model/list/GroupListTest.java
Fixes #182 
* Add error when duplicate groups are added
* Add test cases for increased code coverage
=> Fix edit and add feature

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/StudentId.java, src/main/java/seedu/address/model/person/Year.java, src/main/java/seedu/address/ui/CommandBox.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/model/person/EmailTest.java
fixes #188 
fixes #172 
fixes #169 
fixes #156 
fixes #155
=> General bug fixes

src/main/java/seedu/address/logic/Messages.java
=> Fix multiple argument error message

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/UserPrefs.java
- Change save file name and fixes typos
=> General fixes

docs/UserGuide.md
Fix formatting issues from the previous PR (#203)
=> UG changes pt 2 

src/main/java/seedu/address/model/group/GroupContainsKeywordsPredicate.java
Fixes #206 
Show command is currently case sensitive.
Let's tweak it so that the keywords are found regardless of case
=> Fix bug for show

src/main/java/seedu/address/model/util/SampleDataUtil.java
Fixes #211 
Change Sample Data (cosmetic change)
=> Update Sample Data

docs/DeveloperGuide.md, docs/UserGuide.md
=> Add more verbose documentation

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/ShowCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/Prefix.java, src/main/java/seedu/address/logic/parser/ShowCommandParser.java, src/main/java/seedu/address/model/group/GroupContainsKeywordsPredicate.java, src/main/java/seedu/address/model/list/GroupList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedGroup.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/commands/ShowCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/ListCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/group/GroupContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/group/GroupTest.java, src/test/java/seedu/address/model/list/GroupListTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Fixes #257 
Fixes #258 
* Add test cases
* Add assertions in edit and group-related commands
=> Add tests and assertions

docs/UserGuide.md
=> Fix some bugs in UG

src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
=> Make error message more general

src/test/java/seedu/address/logic/commands/RandomCommandTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/logic/parser/RandomCommandParserTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/MajorTest.java, src/test/java/seedu/address/model/person/NameTest.java, src/test/java/seedu/address/model/person/StudentIdTest.java, src/test/java/seedu/address/model/person/YearTest.java
=> Add more tests

docs/DeveloperGuide.md, docs/UserGuide.md
=> Documentation v1.6

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/RandomCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Major.java, src/main/java/seedu/address/model/person/Year.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/PersonCount.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/test/java/seedu/address/logic/commands/RandomCommandTest.java
=> Code style and quality

src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Fixed the 1 test that was being ignored
=> fix parseCommand_find test

docs/DeveloperGuide.md, src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/parser/ClearCommandParser.java, src/main/java/seedu/address/logic/parser/CommentCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/ExitCommandParser.java, src/main/java/seedu/address/logic/parser/HelpCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Comment.java, src/test/java/seedu/address/stubs/delete/ModelManagerStub.java
=> Improve code quality and declare AI usage

src/test/java/seedu/address/logic/parser/CommentCommandParserTest.java
=> Add test cases for comment parser
